### ISSUE TITLE
Tokens without RANK is not showing

### ISSUE THREAD

**Issue by BlankerL** [cointop-sh/cointop#182] opened 2021-09-26 17:01 UTC
Hello, thank you for your amazing project. I am a newbie to cointop, and found that the tokens without a rank on CoinGecko is not showing and cannot be searched. 

For example, [dForce USD, USX](https://www.coingecko.com/en/coins/token-dforce-usd) do not have a rank, and cannot be found with searching.

Could you please help with this problem?

**Comment by lyricnz** [comment] 2021-09-27 00:13
The token is definitely in the global coins list https://api.coingecko.com/api/v3/coins/list

**Comment by BlankerL** [comment] 2021-09-27 02:53
> The token is definitely in the global coins list https://api.coingecko.com/api/v3/coins/list

Yes, but we could not find this symbol with the search function. Could you have a try?

Maybe you can also have a try on [Bright Token, BRIGHT](https://www.coingecko.com/en/coins/bright-token) for BrightID, I could not find it as well.

**Comment by lyricnz** [comment] 2021-09-27 04:41
Yes, I agree with your finding. It's some kind of issue.

**Comment by lyricnz** [comment] 2021-09-27 05:53
The big list of coins is loaded page-by-page (250 coins per page), maximum of about 10 pages.  It might not be in the first 10 pages. Looking.

**Comment by lyricnz** [comment] 2021-09-27 08:09
There are nearly 10,000 coins on coingecko.  It's not practical to paginate all the way through them (250 at a time) to load all the coins : it will take a long time, and coingecko will block your IP address for hammering their API.

cointop does load all these coins in a single call using https://api.coingecko.com/api/v3/coins/list but that only returns id,symbol,name.

Perhaps we need a way to add coins outside the top 2500?

**Comment by BlankerL** [comment] 2021-09-27 09:03
I have read all the loaded coins on my dashboard, there are 50 pages with 100 on each page, so a total number of 5000 tokens are loaded. 

Several problems are identified:
1. Cross-page sorting of the name is not working. The name/symbol of the tokens is only sorted within the page. 
![image](https://user-images.githubusercontent.com/24969376/134878100-5bebc6c7-25b0-461a-a85a-d6efdd8a45d1.png)

2. Ranks of the tokens are not properly sorted in later pages. For example, the screenshot below is a page 40ish.
![image](https://user-images.githubusercontent.com/24969376/134878028-5e66e5e7-3bb6-4e36-b19e-241a90762399.png)

**Comment by lyricnz** [comment] 2021-09-27 09:35
First of all, I'd like to say thank you for engaging, and submitting bug/enhancement reports.  Open source is based on community involvement.

Secondly, what version of cointop are you using?  I'm on current/dev and I have 36 pages of ~100.  Your screenshot didn't include the footer that shows 36 for me?

1. Yes, it's not a cross-page sort.  That might be confusing, given it's only the "top X" coins.  But you're welcome to submit this is a feature request?  (better in a separate issue)
2. This is because we don't get Rank information from Coingecko for these very-small tokens.  For example https://www.coingecko.com/en/coins/token-dforce-usd has a rank of N/A (the API provides the same data).  This might be because they don't have the data, or the values are so small as to make the Rank rather unstable/chaotic.  Do you have a better suggestion?

Semi-related: I raised a new Issue to request better Search capability (more intuitive use of Symbol vs Name, and "repeat" function to keep searching down the list). #187

**Comment by BlankerL** [comment] 2021-09-27 12:34
Thanks a lot for your contribution. I am also maintaining 2 repos, but not quite familiar with Go.

I am using the latest release ([v1.6.8](https://github.com/miguelmota/cointop/releases/tag/v1.6.8)), and it has 51 pages with over 100 rows per page. 
![image](https://user-images.githubusercontent.com/24969376/134907786-1e14fb9b-3529-4b0b-be30-f37646cf44fb.png)

As the market cap is derived from the Circulating Supply, the tokens without a Circulating Supply do not have a market cap, and cannot be ranked properly, therefore they do not have the Rank information. But what I am saying in my previous comment is that the ranking seems not well-sorted. 

![image](https://user-images.githubusercontent.com/24969376/134908389-37559516-6463-4f57-8708-8b6a109ee68b.png)

For example, the picture above shows the Gaj Finance ranked No. 2124 is surrounded by many project without a rank (showing ranking 10000 in the dashboard). 

Thank you for your opening the new issue for the searching capability.

**Comment by lyricnz** [comment] 2021-09-27 22:16
How bizarre on GAJ!  Shows up in the correct order here, on page 22/41.  Perhaps coingecko is doing something strange we're not handling?   I've been meaning to add some "extremely verbose" HTTP request/response logging for this kind of issue...

**Comment by BlankerL** [comment] 2021-09-28 05:51
Yeah, it's kind of wired and I am not sure about how the data is requested and showed on the dashboard. I will dive into the code when I have time and give it a try.

**Comment by lyricnz** [comment] 2021-09-29 03:58
I added some debug output to my local about what came back from coingecko. I didn't see any rank=0 until the last ~400 coins.  I'd look further, but I can't reproduce your issue. 

Here's what I added to /pkg/api/impl/coingecko/coingecko.go
```
@@ -85,6 +90,10 @@ func (s *Service) GetAllCoinData(convert string, ch chan []apitypes.Coin) error
                                return
                        }

+                       for _, coin := range coins {
+                               log.Debugf("XXX (%d) %s %s rank=%d", i+1, coin.Symbol, coin.Name, coin.Rank)
+                       }
+
                        ch <- coins
                }
        }()
```

**Comment by lyricnz** [comment] 2021-09-30 21:32
@BlankerL can you reproduce if you clean your cache first? `cointop clean`.  It could possibly be a caching issue?

**Comment by BlankerL** [comment] 2021-10-01 17:07
Cool, it could be a cache issue. After cleaning the cache the problem of ranking order was fixed.

**Comment by lyricnz** [comment] 2021-10-02 01:09
Closing as cache-issue. Quite a few improvements made in this area recently.

**Closed by lyricnz** 2021-10-02 01:09 UTC
Labels: bug, enhancement
