### ISSUE TITLE
Currency switch to SEK after showing help menu

### ISSUE THREAD

**Issue by afh** [cointop-sh/cointop#119] opened 2021-04-20 08:58 UTC
**Detailed steps to reproduce:**
* Run current version of cointop (development or 1.6.3)
* Set the currency to EUR (or any other currency than SEK) `C 9`
* Verify that the price menu shows `€[p]rice`
* Open the help menu `?`
* Close the help menu using `q`

**Expected behaviour:**
The price menu still shows `

**Actual behaviour:**
The price menu shows ` kr[p]rice`

**Quick Analysis:**
The shortcut key to set SEK as a currency is `q` 🤔.
Somehow the `q` input to quit the help is also interpreted as a value to set the currency.

I'd be happy to help with putting up a PR, but understand too little at this point about the codebase to know where is issue is originating from and would appreciate any pointers 🐞

**Comment by afh** [comment] 2021-04-20 20:30
It seems that the `q` to quit keybinding in [`cointop/keybindings.go:345`](https://github.com/miguelmota/cointop/blob/master/cointop/keybindings.go#L345) gets overwritten by the keybinding for the different conversion currencies in [`cointop/keybindings.go:360-L363`](https://github.com/miguelmota/cointop/blob/master/cointop/keybindings.go#L360-L363).

**Comment by afh** [comment] 2021-04-20 20:45
It seems that all currency conversion keybindings are set for the help menu as it is possible to open the help menu with `?` and then close it with `w` and at the same time set USD.

The issue seems to stem from the fact that all menus share the same [underlying view](https://github.com/miguelmota/cointop/blob/master/cointop/cointop.go#L32) with the [same name](https://github.com/miguelmota/cointop/blob/master/cointop/menu.go#L10).

In your mind @miguelmota would it be better to create different views for each menu or allow for the shared menu view name to be set as necessary—the latter possibly causing other issues down the line (just a hunch)…

**Comment by miguelmota** [comment] 2021-04-25 00:11
Ah this is a bug indeed. Ideally the currency selection menu is a some form of a scrollable select menu (ie use arrow keys to navigate, spacebar to toggle selection, enter to select or save selection) but that's obviously more involved. The fix for this particular issue would be to create separate menu views and bind `q` to the appropriate action (the former of what you were suggesting)

@afh

**Comment by pelim** [comment] 2021-05-16 13:17
looks like an issue with the active state of the currency menu and the corresponding keybinding

Keypress "q" is for "SEK"

**Comment by lyricnz** [comment] 2021-09-29 22:12
I can reproduce this - though with recent change to add Satoshi (SATS) that's now the one that is 'q'

**Comment by miguelmota** [comment] 2022-03-19 06:26
No longer an issue. Closing

**Closed by miguelmota** 2022-03-19 06:26 UTC
Labels: bug
